import { z } from "zod";
import type { CommandMeta } from "@/src/core/types";
import {
	DEFAULT_DISK_SIZE,
	DEFAULT_MEMORY,
	DEFAULT_VCPU,
} from "@/src/utils/constants";
import {
	cvmIdOption,
	interactiveOption,
	uuidOption,
} from "@/src/core/common-flags";

export const deployCommandMeta: CommandMeta = {
	name: "deploy",
	category: "deploy",
	description: "Deploy new CVM or update existing one",
	stability: "stable",
	arguments: [],
	options: [
		cvmIdOption,
		uuidOption,
		interactiveOption,
		{
			name: "debug",
			description: "Enable debug logging",
			type: "boolean",
			target: "debug",
			group: "advanced",
		},
		{
			name: "name",
			shorthand: "n",
			description: "CVM name (defaults to directory name)",
			type: "string",
			target: "name",
			group: "basic",
		},
		{
			name: "compose",
			shorthand: "c",
			description: "Path to Docker Compose file (default: docker-compose.yml)",
			type: "string",
			target: "compose",
			group: "basic",
		},
		{
			name: "instance-type",
			shorthand: "t",
			description: "Instance type (e.g., tdx.small, auto-selected if omitted)",
			type: "string",
			target: "instanceType",
			group: "basic",
		},
		{
			name: "vcpu",
			description: "Use --instance-type instead",
			type: "string",
			target: "vcpu",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "memory",
			description: "Use --instance-type instead",
			type: "string",
			target: "memory",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "disk-size",
			description: `Disk size with unit (e.g., 50G, default: ${DEFAULT_DISK_SIZE}GB)`,
			type: "string",
			target: "diskSize",
			group: "advanced",
		},
		{
			name: "fs",
			description: "Filesystem type (ext4 or zfs, default: zfs)",
			type: "string",
			target: "fs",
			group: "advanced",
		},
		{
			name: "image",
			description: "OS image version (auto-selected if omitted)",
			type: "string",
			target: "image",
			group: "advanced",
		},
		{
			name: "region",
			shorthand: "r",
			description: "Preferred region (e.g., us-west, auto-selected if omitted)",
			type: "string",
			target: "region",
			group: "basic",
		},
		{
			name: "node-id",
			description: "Node ID (auto-selected if omitted)",
			type: "string",
			target: "nodeId",
			group: "advanced",
		},
		{
			name: "env",
			shorthand: "e",
			description:
				"Environment variable (KEY=VALUE) or env file path (repeatable)",
			type: "string[]",
			target: "env",
			group: "basic",
		},
		{
			name: "env-file",
			description: "Use -e instead",
			type: "string",
			target: "envFile",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "kms",
			description: "KMS type: phala (default), ethereum/eth, or base",
			type: "string",
			target: "kms",
			group: "basic",
		},
		{
			name: "kms-id",
			description: "Use --kms instead",
			type: "string",
			target: "kmsId",
			deprecated: true,
			group: "deprecated",
		},
		{
			name: "custom-app-id",
			description: "Custom App ID (requires --nonce for PHALA KMS)",
			type: "string",
			target: "customAppId",
			group: "advanced",
		},
		{
			name: "nonce",
			description:
				"Nonce for deterministic app_id (requires --custom-app-id, PHALA KMS only)",
			type: "string",
			target: "nonce",
			group: "advanced",
		},
		{
			name: "pre-launch-script",
			description: "Path to pre-launch script",
			type: "string",
			target: "preLaunchScript",
			group: "advanced",
		},
		{
			name: "private-key",
			description: "Private key for signing transactions.",
			type: "string",
			target: "privateKey",
			group: "advanced",
		},
		{
			name: "rpc-url",
			description: "RPC URL for the blockchain.",
			type: "string",
			target: "rpcUrl",
			group: "advanced",
		},
		{
			name: "skip-onchain-tx",
			description:
				"Skip the on-chain transaction (use when tx was submitted externally)",
			type: "boolean",
			target: "skipOnchainTx",
			group: "advanced",
		},
		{
			name: "wait",
			description: "Wait for deployment/update completion",
			type: "boolean",
			target: "wait",
			group: "basic",
		},
		{
			name: "ssh-pubkey",
			description: "SSH public key path (default: ~/.ssh/id_rsa.pub)",
			type: "string",
			target: "sshPubkey",
			group: "basic",
		},
		{
			name: "dev-os",
			description: "Use dev OS image (requires SSH key)",
			type: "boolean",
			target: "devOs",
			negatedName: "no-dev-os",
			group: "basic",
		},
		{
			name: "public-logs",
			description: "Make CVM logs publicly accessible (default: true)",
			type: "boolean",
			target: "publicLogs",
			negatedName: "no-public-logs",
		},
		{
			name: "public-sysinfo",
			description: "Make CVM system info publicly accessible (default: true)",
			type: "boolean",
			target: "publicSysinfo",
			negatedName: "no-public-sysinfo",
		},
		{
			name: "listed",
			description: "List CVM on the public Trust Center (default: false)",
			type: "boolean",
			target: "listed",
			negatedName: "no-listed",
		},
	],
	examples: [
		// --- New Deployment Examples ---
		{
			name: "Deploy new CVM",
			value: "phala deploy",
		},
		{
			name: "Deploy with environment variables",
			value: "phala deploy -e NODE_ENV=production -e DEBUG=true",
		},
		{
			name: "Deploy with env file",
			value: "phala deploy -e .env",
		},
		{
			name: "Deploy with specific instance type",
			value: "phala deploy --instance-type tdx.medium",
		},
		{
			name: "Deploy to specific region",
			value: "phala deploy --region us-west",
		},
		{
			name: "Deploy with Ethereum KMS",
			value: "phala deploy --kms ethereum --private-key <key> --rpc-url <url>",
		},
		// --- Update Existing CVM Examples ---
		{
			name: "Update existing CVM by ID",
			value: "phala deploy --cvm-id app_abc123",
		},
		{
			name: "Update CVM with new compose file and env",
			value:
				"phala deploy --cvm-id my-app --compose ./new-docker-compose.yml -e .env",
		},
		{
			name: "Update CVM and wait for completion",
			value: "phala deploy --cvm-id app_abc123 --wait",
		},
		{
			name: "Update CVM from phala.toml",
			value: "phala deploy",
		},
		// --- Privacy Settings Examples ---
		{
			name: "Deploy with logs and sysinfo disabled",
			value: "phala deploy --no-public-logs --no-public-sysinfo",
		},
		{
			name: "Deploy and list on Trust Center",
			value: "phala deploy --listed",
		},
		{
			name: "Update existing CVM to disable logs",
			value: "phala deploy --cvm-id app_123 --no-public-logs",
		},
	],
};

export const deployCommandSchema = z.object({
	compose: z.string().optional(),
	json: z.boolean().default(false),
	debug: z.boolean().default(false),
	apiToken: z.string().optional(),
	name: z.string().optional(),
	instanceType: z.string().optional(),
	vcpu: z.string().optional(),
	memory: z.string().optional(),
	diskSize: z.string().optional(),
	fs: z.enum(["ext4", "zfs"]).optional(),
	image: z.string().optional(),
	region: z.string().optional(),
	nodeId: z.string().optional(),
	env: z.array(z.string()).optional(),
	envFile: z.string().optional(),
	interactive: z.boolean().default(false),
	kms: z.enum(["phala", "ethereum", "eth", "base"]).default("phala"),
	kmsId: z.string().optional(),
	cvmId: z.string().optional(),
	customAppId: z.string().optional(),
	nonce: z.string().optional(),
	preLaunchScript: z.string().optional(),
	privateKey: z.string().optional(),
	rpcUrl: z.string().optional(),
	skipOnchainTx: z.boolean().default(false),
	wait: z.boolean().default(false),
	sshPubkey: z.string().optional(),
	devOs: z.boolean().optional(),
	publicLogs: z.boolean().optional(),
	publicSysinfo: z.boolean().optional(),
	listed: z.boolean().optional(),
});

export type DeployCommandInput = z.infer<typeof deployCommandSchema>;
